//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CS.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DISP_DIALOG                 102
#define IDD_SET_DIALOG                  129
#define IDD_CAN_DIALOG                  130
#define IDD_LOGIN_DIALOG                131
#define IDD_SET_DIALOG_FGYSJ            133
#define IDD_SET_DIALOG_FMAF             134
#define IDD_SET_DIALOG_DQ               135
#define IDR_MAINFRAME                   136
#define IDB_BITMAP_LOGO                 144
#define IDB_BITMAP_URGENTBTN            145
#define IDB_BITMAP_ONEKEYSTOP           146
#define IDB_BITMAP_STOPKUCTRL           147
#define IDB_BITMAP_STOPKUCTRL1          148
#define IDB_BITMAP_STARTKUCTRL          148
#define IDB_BITMAP1                     151
#define IDB_BITMAP_QUIT                 151
#define IDC_LIST_ON_ITEM                1000
#define IDC_EDIT_ON_NUM                 1001
#define IDC_EDIT_ON_DWKD                1002
#define IDC_STATIC_ON_DIR               1003
#define IDC_BUTTON_ON_ADD               1006
#define IDC_BUTTON_ON_INS               1007
#define IDC_BUTTON_ON_DEL               1008
#define IDC_LIST_CTRL_ON_PROP           1009
#define IDC_LIST_CTRL_OFF_PROP          1010
#define IDC_RADIO_PROP1                 1011
#define IDC_RADIO_PROP2                 1012
#define IDC_LIST_CID_ITEM               1016
#define IDC_LISTRcvView                 1018
#define IDC_EDIT_CID_NUM                1018
#define IDC_EDIT_KD                     1021
#define IDC_EDIT_UID                    1021
#define IDC_EDIT_RCVMSG                 1021
#define IDC_EDIT_KU_SUM                 1021
#define IDC_EDIT_YSJ                    1021
#define IDC_EDIT_PWD                    1022
#define IDC_BUTTON_SET                  1022
#define IDC_BUTTON_ID_ADD               1022
#define IDC_EDIT_SHUIB                  1022
#define IDC_EDIT_SB                     1022
#define IDC_EDIT_XQ                     1023
#define IDC_EDIT_RCVMSG2                1023
#define IDC_BUTTON_ID_DEL               1024
#define IDC_EDIT_PQ                     1024
#define IDC_LIST_CID                    1025
#define IDC_EDIT_AF                     1025
#define IDC_EDIT_CID_ID                 1026
#define IDC_EDIT_AB                     1026
#define IDC_CHECK_CID                   1027
#define IDC_CHECK_KU_SUM                1027
#define IDC_EDIT_DW                     1027
#define IDC_EDIT_TEMP_NUM               1028
#define IDC_BUTTON_START_ON             1028
#define IDC_BUTTON_DO_PT_ON2            1029
#define IDC_EDIT_TEMP_UP                1029
#define IDC_BUTTON_OPEN                 1030
#define IDC_EDIT_KU_T_DN                1030
#define IDC_EDIT_TEMP_DN                1030
#define IDC_BUTTON_CLOSE                1031
#define IDC_BUTTON_KU_OK                1031
#define IDC_EDIT_TEMP_DN2               1032
#define IDC_BUTTON_KU_DEL               1033
#define IDC_EDIT_TEMP_SUM               1034
#define IDC_BUTTON_OPEN2                1034
#define IDC_BUTTON_FGYD_ADD             1035
#define IDC_BUTTON_START_OFF            1035
#define IDC_EDIT_TEMP_UP2               1035
#define IDC_COMBO_KU_NUM                1036
#define IDC_BUTTON_YSJ_OK               1036
#define IDC_LIST_KU                     1037
#define IDC_BUTTON_YSJ_DEL              1037
#define IDC_BUTTON_FGYD_EDIT            1038
#define IDC_EDIT_KU_WU                  1039
#define IDC_BUTTON_CLOSE2               1039
#define IDC_BUTTON_YSJ_EDIT             1039
#define IDC_BUTTON_FGYD_DEL             1040
#define IDC_BUTTON_SEND2                1040
#define IDC_BUTTON_DO_ON2               1041
#define IDC_BUTTON_STOP_ON              1041
#define IDC_EDIT_KU_FY                  1041
#define IDC_RADIO_KU1                   1042
#define IDC_RADIO_KU2                   1043
#define IDC_EDIT_KU_HQ                  1044
#define IDC_EDIT_FGYD_H1                1047
#define IDC_EDIT_FGYD_M1                1048
#define IDC_EDIT_FGYD_H2                1049
#define IDC_EDIT_FGYD_M2                1050
#define IDC_EDIT_KU_FJ                  1051
#define IDC_EDIT_KU_YSJ                 1052
#define IDC_LIST_FG                     1053
#define IDC_EDIT_KU_FJ2                 1053
#define IDC_EDIT_AN_ALARM               1053
#define IDC_EDIT_FG_KU_NUM              1054
#define IDC_BUTTON_TEMP_TEST            1056
#define IDC_EDIT_PROP                   1058
#define IDC_EDIT_JZ_DATA                1058
#define IDC_EDIT_AF_KD                  1058
#define IDC_EDIT_KU_ON_MAX              1058
#define IDC_BUTTON_START_TEMP_CTRL      1059
#define IDC_BUTTON_START_TEMP_CTRL2     1060
#define IDC_BUTTON_STOP_TEMP_CTRL       1060
#define IDC_RADIO_KU_CTRL1              1060
#define IDC_RADIO_KU_CTRL2              1061
#define IDC_BUTTON_SUSPEND_TEMP_CTRL    1061
#define IDC_RADIO_KU_CTRL3              1062
#define IDC_BUTTON_RESUME_TEMP_CTRL     1062
#define IDC_EDIT_CHSH                   1063
#define IDC_RADIO_WORK_MODE1            1066
#define IDC_RADIO_WORK_MODE2            1067
#define IDC_RADIO_WORK_MODE3            1068
#define IDC_TAB_SET_DLG                 1069
#define IDC_LIST_YSJ                    1070
#define IDC_RADIO_PROP_ZU_1             1071
#define IDC_RADIO_PROP_ZU_2             1072
#define IDC_RADIO_PROP_ZU_3             1073
#define IDC_EDIT_PROP_ZU_YSJ            1074
#define IDC_EDIT_PROP_ZU_KU             1075
#define IDC_EDIT_PROP_ZU_GX             1076
#define IDC_BUTTON_RST_KU_PROP          1076
#define IDC_BUTTON_TIME_CTRL            1078
#define IDC_BUTTON_URGENT_STOP          1078
#define IDC_CHECK_ALL_KU                1079
#define IDC_RADIO_AF_AUTO1              1083
#define IDC_RADIO_AF_AUTO2              1084
#define IDC_RADIO_AF_AUTO3              1085
#define IDC_EDIT_AF_NUM                 1089
#define IDC_BUTTON_AF_OK                1090
#define IDC_BUTTON_AF_DEL               1091
#define IDC_LIST_AF                     1092
#define IDC_EDIT_DQ_NUM                 1093
#define IDC_RADIO_DQ_NC1                1094
#define IDC_RADIO_DQ_NC2                1095
#define IDC_LIST_DQ                     1097
#define IDC_EDIT_DQ_ITEM                1098
#define IDC_BUTTON_DQ_OK                1099
#define IDC_BUTTON_DQ_DEL               1100
#define IDC_BUTTON_UR_PHONE_OK          1101
#define IDC_BUTTON_UR_PHONE_DEL         1102
#define IDC_CHECK_YSJ_WT                1106
#define IDC_LIST_TEMP                   1107
#define IDC_LIST_JZ_TEMP                1107
#define IDC_CHECK_YSJ_RT                1108
#define IDC_RADIO_NC1                   1108
#define IDC_RADIO_NC2                   1109
#define IDC_EDIT_YW                     1110
#define IDC_EDIT_TEST_TO_CTRL           1110
#define IDC_EDIT_KU_ALL_ZU              1110
#define IDC_BUTTON_START_ONEKEY         1111
#define IDC_BUTTON_JZ_TEMP_OK           1111
#define IDC_LIST_CID_CTRL               1112
#define IDC_BUTTON_JZ_TEMP_DEL          1112
#define IDC_LIST_CID_ITEM_CTRL          1113
#define IDC_EDIT_CID_NUM_CTRL           1114
#define IDC_EDIT_CID_ID_CTRL            1115
#define IDC_BUTTON_TEST_OPEN_CTRL       1116
#define IDC_BUTTON_TEST_CLOSE_CTRL      1117
#define IDC_BUTTON_TEST_CX_CTRL         1120
#define IDC_BUTTON_STOP_REF_CTRL        1121
#define IDC_BUTTON_STOP_ONEKEY          1122
#define IDC_BUTTON_REFER_ALL_CTRL       1123
#define IDC_BUTTON_TEST_TO_CTRL         1124
#define IDC_CHECK_KU_ALL_ZU             1125
#define IDC_CHECK_ONLY_OFF_FJ           1126
#define IDC_CHECK_KU_ON_MAX             1131
#define IDC_LIST_KU_CTRL                1133
#define IDC_LIST_YSJ_CTRL               1134
#define IDC_CHECK_RUKU_ING              1136
#define IDC_BUTTON_RUKU_CLEAR           1137
#define IDC_COMBO_RUKU                  1138
#define IDC_BUTTON_CTRL_OPEN            1139
#define IDC_BUTTON_CTRL_CLOSE           1140
#define IDC_CHECK_MY_PHONE              1140
#define IDC_EDIT_MY_PHONE               1141
#define IDC_EDIT_UR_PHONE               1142
#define IDC_LIST_UR_PHONE               1143
#define IDC_CHECK_CAN_SIMULATE          1144
#define IDC_CHECK_TEMP_SIMULATE         1145
#define IDC_EDIT_TEMP_SIM_ZH            1147
#define IDC_EDIT_TEMP_SIM_X             1148
#define IDC_CHECK_TEMP_SIM_SIGN         1149
#define IDC_BUTTON_TEMP_SIM_OK          1150
#define IDC_STATIC_TEMP_SIM_X           1151
#define IDC_STATIC_TEMP_SIM_LOGO        1152
#define IDC_EDIT_CUR_TIME               1153
#define IDC_STATIC_TIME_CTRL            1154
#define IDC_STATIC_PSS                  1155
#define IDC_STATIC_CS                   1156
#define IDC_STATIC_SC                   1158
#define IDC_RADIO_TIME_ST_ON            1159
#define IDC_RADIO_TIME_ST_OFF           1160
#define IDC_RADIO_ALL_OFF_OFF           1161
#define IDC_RADIO_ALL_OFF_ON            1162
#define IDC_RADIO_TIME_OFF_TIME         1163
#define IDC_RADIO_TIME_OFF_TEMP         1164
#define IDC_RADIO_ALL_OFF_NO            1165
#define IDC_EDIT_CID_DQ                 1166
#define IDC_EDIT_CID_DQ_CTRL            1167
#define IDC_BUTTON_KU_ON_MANUAL         1182
#define IDC_BUTTON_KU_OFF_MANUAL        1183
#define IDC_COMBO_KU_NUM_MANUAL         1184
#define IDC_BUTTON_CX_TEXT              1186
#define IDC_LIST_DISP_TEXT              1187
#define IDC_EDIT_KU_TEMP_CHANGE_DAYS    1188
#define IDC_CHECK_KU_TEMP_CHANGE        1191
#define IDC_LIST_KU_TEMP_CHANGE         1192
#define IDC_STATIC_KU_TEMP_CHANGE_DAYS  1193
#define IDC_STATIC_KU_TEMP_CHANGE_DAYS2 1194
#define IDC_EDIT_TEMP_UP_CTRL           1195
#define IDC_EDIT_TEMP_DN_CTRL           1196
#define IDC_CHECK_TEMP_UP_CTRL          1197
#define IDC_CHECK_TEMP_DN_CTRL          1198
#define IDC_BUTTON_TEMP_UP_DN_CTRL      1199
#define IDC_BUTTON_AF_OK2               1199
#define IDC_BUTTON_AF_DEL2              1200
#define IDC_OCX_URGENT                  1201
#define IDC_BUTTON_WMP_ST               1203
#define IDC_BUTTON_WMP_SP               1204
#define IDC_BUTTON_WMP_UR               1205
#define IDC_BUTTON_WMP_UR2              1206
#define IDC_BUTTON_WMP_STOP             1206
#define IDC_BUTTON_OPEN_ANS             1207
#define IDC_BUTTON_CLOSE_ANS            1208
#define IDC_LIST_ANS_CTRL               1209
#define IDC_CHECK_ANS_SUM               1210
#define IDC_EDIT_ANS_SUM                1211
#define IDC_COMBO_JZ_TEMP_NUM           1212
#define IDC_EDIT_TEMP_DN_S              1213
#define IDC_CHECK_KU_TIME_S             1215
#define IDC_EDIT_KU_TIME_S              1216
#define IDC_EDIT_AF_TIME                1217
#define IDC_EDIT_AF_FD                  1218
#define IDC_EDIT_AF_SD                  1219
#define IDC_LIST_AF2                    1220
#define IDC_EDIT_AF_TIME2               1221
#define IDC_CHECK_ON_OFF_CYCLE          1221
#define IDC_BUTTON_SETKU_YSJ            1222
#define IDC_BUTTON_SETKU_FY             1223
#define IDC_BUTTON_SETKU_HQ             1224
#define IDC_BUTTON_SETYSJ_AF            1224
#define IDC_BUTTON_SETKU_FJ             1225
#define IDC_BUTTON_SETYSJ_AB            1225
#define IDC_BUTTON_ONLY_FY              1225
#define IDC_BUTTON_ONLY_FJ              1226
#define IDC_CHECK_SMS_PROP              1228
#define IDC_CHECK_KU_SET_TEMP_CHANGE_HOUR 1230
#define IDC_EDIT_KU_SET_TEMP_CHANGE_HOUR 1231
#define IDC_LIST_DELAY3                 1232
#define IDC_COMBO_YSJ_MANUAL            1234
#define IDC_BUTTON_YSJ_OFF_MANUAL       1235
#define IDC_CHECK_YSJ_MANUAL            1236
#define IDC_BUTTON_MANUAL_YSJ_STOP      1237
#define IDC_BUTTON2                     1238
#define IDC_BUTTON_YSJ_ON_MANUAL        1238
#define IDC_BUTTON_SETTEMP_DNS          1238
#define IDC_EDIT_YSJ_PRIORITY           1239
#define IDC_CHECK_YSJ_PRIORITY          1240
#define IDC_EDIT_KU_YSJ_KUNUM           1241
#define IDC_EDIT_KU_YSJ_YSJNUM          1242
#define IDC_BUTTON_KU_YSJ_YES           1243
#define IDC_BUTTON_KU_YSJ_NO            1244
#define IDC_LIST_KU_YSJ                 1245
#define IDC_CHECK_KU_YSJ                1246
#define IDC_BUTTON_SETKU_MODE           1247
#define IDC_BUTTON_SETTEMP_JZ           1248
#define IDC_BUTTON_SETTEMP_NUM          1249
#define IDC_STATIC_LOGO                 1250
#define IDC_BUTTON_QUIT                 1251

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1252
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
